services:
  mongo:
    image: mongo:latest
    container_name: 'chat_db'
    # env_file:
    #   - .env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    #   - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: 'chat_backend'
    ports:
      - 3008:3008
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongodata:
    driver: local
